### ISSUE TITLE
Implement the unit normal tag properly

### ISSUE THREAD

**Issue by geoffrey4444** [geoffrey4444/spectre#1]
Currently, this branch uses a hack for computing the face unit normal one-form. `FaceNormal.hpp` near line 78 defines a simple tag `UnitFaceNormal` and a compute tag `UnitFaceNormalCompute`, and two more for `UnitFaceNormalVector` and `UnitFaceNormalVectorCompute` to get the unit normal vector.

Items to fix:

  * `UnitFaceNormalCompute` duplicates `Normalize<UnnormalizedFaceNormal, Magnitude<UnnormalizedFaceNormal>` with the addition of inheriting off of a new simple tag `UnitFaceNormal`. Instead, as discussed in a previous spectre meeting, `Normalize<>` in `Magnitude.hpp` should inherit off of a simple tag, so that any time your `Normalize<>` something, you can access the result with a SimpleTag.

* `UnitFaceNormalVectorCompute` should probably not be necessary. Instead, `IndexManipulation.hpp` has a function `raise_or_lower_index` that should have a generic compute item that inherits off of a generic `db::SimpleTag`

**Comment by prayush** [comment]
A fix is up via #20
