### ISSUE TITLE
LocalLaxFriedrichs  assumes char speeds are std::array<DataVectors>, but GH char speeds are Variables of CharSpeed<CharField>

### ISSUE THREAD

**Issue by geoffrey4444** [geoffrey4444/spectre#11]
Either GH char speeds need to be `std::array<DataVector>` or the code that uses the different numerical fluxes needs to be updated, along with all the other fluxes

**Comment by prayush** [comment]
The second choice seems more right, however, maybe get the first one working for now, and swap `std::array` out to `Variables` everywhere later.

**Comment by geoffrey4444** [comment]
I agree with your plan..think tomorrow AM I can get the upwind flux working

**Comment by geoffrey4444** [comment]
Char speeds are now std::array<DataType, 4> for GeneralizedHarmonic.
