### ISSUE TITLE
Fix scalar wave

### ISSUE THREAD

**Issue by geoffrey4444** [geoffrey4444/spectre#14]
Our initialization hard-coded some stuff for KerrSchild/GeneralizedHarmonic, and this broke EvolveScalarWave. This needs to be fixed so all test executables compile. @prayush can you take a look?

**Comment by prayush** [comment]
This is because we add `GeneralizedHarmonic` specific variables to interfaces, e.g.
```
Tags::InterfaceComputeItem<
          Tags::BoundaryDirectionsExterior<dim>,
          gr::Tags::SpatialMetricCompute<dim, Inertial, DataVector>>,
```
This needs `gr::Tags::SpacetimeMetric` in the box, which I guess not every evolution system is inserting.

**Comment by geoffrey4444** [comment]
I suspect we can create a new initialization step in GeneralizedHarmonic/Initialize.hpp so that NonConservativeInterface.hpp can be system-agnostic...

**Comment by prayush** [comment]
The trouble is that `System::magnitude_tag` needs to be put onto Interfaces. `GeneralizedHarmonic` uses `magnitude_tag = Tags::NonEuclideanMagnitude`, which needs curved spacetime quantities like `InverseSpatialMetric`. The scalar wave system does not need those, as it uses `magnitude_tag = Tags::EuclideanMagnitude`.

Therefore, I think we want two versions oft `Evolution/Initialization/NonConservativeInterface.hpp`: (a) `NonConservativeInterface.hpp` for flat spacetimes, and (b) `NonConservativeInterfaceCurvedSpacetime.hpp`.

What do you think?

**Comment by geoffrey4444** [comment]
I think you're right, but isn't it even worse? Not every system with curved spacetime needs the generalized harmonic constraint damping parameters, right? 

Anyway, for now I just pushed a commit with NonConservativeInterface.hpp going back to what it was in my PR #1365 on the main spectre repo, with GeneralizedHarmonic using a new file GeneralizedHarmonicInterface.hpp. This way everything compiles.

Later on, perhaps there's a way to generalized GeneralizedHarmonicInterface.hpp for curved scalar wave, but I don't think that's high priority. So close this issue for now?

**Comment by prayush** [comment]
You're right, this solution is not perfect. Buts its *only* the constraint damping parameter that need to be moved out of `GeneralizedHarmonicInterface.hpp` to make it more general. We can find a way to do that later.

Thanks for taking care of this. I'm closing the issue for now.
