### ISSUE TITLE
Understand & fix blowing up errors

### ISSUE THREAD

**Issue by geoffrey4444** [geoffrey4444/spectre#15]
When you evolve Kerr-Schild, the errors blow up, and after a few time steps, they appear to be growing exponentially in time. We need more diagnostics (errors in all variables vs analytic solution, constraints) to help diagnose, along with ParaView to see where the errors are largest, if anywhere.

**Comment by prayush** [comment]
@geoffrey4444 - How can I reproduce this? Currently if I run:

```
$ pwd
/home/prayush/src/spectre/spectre_EvolveGeneralizedHarmonic/build_clang/RUN

$ ../bin/EvolveGeneralizedHarmonic --input-file ../../tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml 
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: MPI_THREAD_FUNNELED (desired: MPI_THREAD_FUNNELED)
Charm++> Running in SMP mode: numNodes 1,  1 worker threads per process
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.8.0-0-ga36028e
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (24-way SMP).
Charm++> cpu topology info is gathered in 0.002 seconds.

Executing '../bin/EvolveGeneralizedHarmonic' using 1 processors.
Date and time at startup: Mon Mar  4 15:30:50 2019

SpECTRE Build Information:
Version:                      0.0.0
Compiled on host:             wheeler.caltech.edu
Compiled in directory:        /home/prayush/src/spectre/spectre_EvolveGeneralizedHarmonic/build_clang
Source directory is:          /home/prayush/src/spectre/spectre_EvolveGeneralizedHarmonic
Compiled on git branch:       EvolveKerrSchild2
Compiled with git hash:       094f41c452d59b8cc2711c2ebcb80b88f8e050d5
Linked on:                    Mon Mar  4 14:18:19 2019


Done!
CkWallTimer in seconds 4.207482
Date and time at completion: Mon Mar  4 15:30:55 2019

[Partition 0][Node 0] End of program
```
I see no output diagnostic at all:
```
$ ls -l
total 0
$ 

```

**Comment by geoffrey4444** [comment]
You need to edit the input file to observe more often and to observe at t=0. Then you'll get h5 files with the error in psi vs the analytic solution as volume data and a reduction to just a double vs time.

Here's a screenshot from ParaView I made. The errors blow up on the interfaces, so I suspect something is wrong with the upwind flux. This might mean we should prioritize getting LocalLaxFriedrichs working as a point of comparison.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/867015/53770345-9a383400-3e93-11e9-855d-5df36b87a360.png">

**Comment by geoffrey4444** [comment]
Rewritten upwind flux appears to fix this, so I'm closing this. We can reopen if we see errors blowing up on boundaries in the future.
