### ISSUE TITLE
Properly add quantities to interface

### ISSUE THREAD

**Issue by geoffrey4444** [geoffrey4444/spectre#3]
Currently, the branch incorrectly adds `Tags::Interface<>` in `face_tags` in `NonConservativeInterface.hpp`. You should only add `InterfaceComputeItems` here or the code won't compile. 

The underlying compute items should probably add the line `using base = using base = InverseSpacetimeMetric<SpatialDim, Frame, DataType>;` (replacing `InverseSpatialMetric` with the simple tag the compute tag inherits from).

**Comment by geoffrey4444** [comment]
I added `using base =` for all the relevant compute items I could find, and now I don't get Interface<> DataBox errors. I also removed all Tags::Interface<> tags from the interface's compute_tags list.

Can this issue be closed?

**Comment by prayush** [comment]
This is probably fixed between our commits. I am closing the issue.
