### ISSUE TITLE
Don't use duplicated tags for space and time derivatives

### ISSUE THREAD

**Issue by geoffrey4444** [geoffrey4444/spectre#5]
`ComputeGhQuantities.hpp` defines tags `DerivSpatialMetric`, `TimeDerivSpatialMetric` simple tags and corresponding compute tags that inherit from them. Instead, the compute tags should inherit from the built-in `deriv<>` and `dt<>` tags. Similarly for lapse and shift space and time derivatives.

Also, maybe `TimeDerivSpatialMetricCompute` should be renamed?

**Comment by prayush** [comment]
> Also, maybe `TimeDerivSpatialMetricCompute` should be renamed?

I suggest `TimeDerivXCompute` --> `TimeDerivXFromGhVarsCompute` (and similarly, `DerivXCompute` --> `DerivXFromGhVarsCompute`) for `X=Lapse, Shift, SpatialMetric`. If you like the name, I'll push a rename commit. If now, feel free to suggest better nomenclature.

**Comment by geoffrey4444** [comment]
Can we close this issue, @prayush?

**Comment by prayush** [comment]
yes
