### ISSUE TITLE
Make GeneralizedHarmonic observer not depend on Kerr Schild

### ISSUE THREAD

**Issue by geoffrey4444** [geoffrey4444/spectre#8]
Currently `Evolution/Systems/GeneralizedHarmonic/Observe.hpp` assumes Kerr-Schild to get the spacetime metric for observation. Once the new solution wrapper is in place, this will have to be updated

**Comment by geoffrey4444** [comment]
Technically, the observer only uses KerrSchild to figure out what tags to ask for from the analytic solution. Evolving with flat space actually works (well, works as well as KerrSchild does).

Line 129 of GeneralizedHarmonic/Observe.hpp should probably be changed to not go through Kerr-Schild before closing this issue, but this issue isn't stopping us from trying to evolve flat space.

**Comment by prayush** [comment]
Btw, this is the same line 

```
const auto& exact_solution_variables = exact_solution.variables(
          inertial_coordinates, time.value(),
          gr::Solutions::KerrSchild::tags<DataVector>{});
```

that also makes `GeneralizedHarmonic/Initialize.hpp` (line 179-183) not be generally valid for all `AnalyticSolutions`. So a fix here should be carried over there too. 

The way to generalize is to get to the solution through the base class `OptionTags::AnalyticSolutionBase` *only*. I don't see how one can access `tags` inside `KerrSchild` through the base class though. The only thing I can see possible is extracting these tags out of`Metavariables` through `Metavariables::analytic_solution_tag`. Using the `analytic_solution_tag` directly in `Observe.hpp` would again make it depend on something we don't want it to. So I extract `KerrSchild`'s tags inside `Metavariables` itself into `analytic_tags_internal` and use that in `Observe.hpp` and `Initialize.hpp`. 

I've pushed this [commit](https://github.com/geoffrey4444/spectre/commit/79df2ea60f5c7d109c88d17c78a2d471b0787e56) as a fix. @geoffrey4444 If you find it ok, maybe close this issue?

**Comment by geoffrey4444** [comment]
After talking with Larry, the right thing to do is to not use an analytic solution's tags at all, but instead to add the list of tags to PointwiseFunctions/GeneralRelativity/Tags.hpp. This is because the list of tags to extract should always be the same, i.e. should not depend on which solution you use. I'm going to push this fix after reverting your commit

**Comment by prayush** [comment]
That makes sense too. Please change this at both places since your at it, thanks!

**Comment by geoffrey4444** [comment]
Done
